const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const projectRoot = path.resolve(__dirname, '..')
const practiceScript = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.js'), 'utf8')
const practiceTemplate = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.wxml'), 'utf8')
const practiceStyle = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.wxss'), 'utf8')
const paintWxs = fs.readFileSync(path.join(projectRoot, 'pages/paint.wxs'), 'utf8')
const markWordBlock = paintWxs.slice(paintWxs.indexOf('markWord:'))

test('practice page exposes a word-new mode driven by the task type route option', () => {
  assert.match(practiceScript, /taskType:\s*'recitation'/)
  assert.match(practiceScript, /isWordNewMode/)
  assert.match(practiceScript, /options\.taskType === 'word'/)
})

test('word-new starts each card in an unrevealed "认识不" quiz state', () => {
  assert.match(practiceScript, /item\.revealed = false/)
  assert.match(practiceScript, /item\.hinted = false/)
  assert.match(practiceScript, /item\.mistaken = false/)
  assert.match(practiceTemplate, /wx:if="{{!item\.revealed}}"/)
  assert.match(practiceTemplate, /提示一下/)
  assert.match(practiceTemplate, /认识/)
  assert.match(practiceTemplate, /不认识/)
})

test('word-new audio progress uses the three dots as one-time stage markers', () => {
  assert.match(practiceScript, /三个点分别对应：问答页读词、详情页读词、详情页读例句/)
  assert.match(practiceScript, /startWordReading\s*\(index\)/)
  assert.match(practiceScript, /\['contents\[' \+ index \+ '\]\.readCount'\]: 1/)
  assert.doesNotMatch(practiceScript, /count < 3/)
  assert.match(practiceScript, /playDetailIntro\s*\(index\)/)
  assert.match(practiceScript, /setWordReadCount\(index, 2\)/)
  assert.match(practiceScript, /setWordReadCount\(index, 3\)/)
  assert.match(practiceScript, /getExampleAudio\s*\(index\)/)
  assert.match(practiceTemplate, /item\.readCount >= 1/)
  assert.match(practiceTemplate, /item\.readCount >= 2/)
  assert.match(practiceTemplate, /item\.readCount >= 3/)
  assert.doesNotMatch(practiceTemplate, /<view class="wn-dots"><view class="wn-dot-on"><\/view><view class="wn-dot-on"><\/view><view class="wn-dot-on"><\/view><\/view>/)
})

test('提示一下 reveals the example translation and plays its audio without revealing the card', () => {
  assert.match(practiceScript, /showHint\s*\(/)
  assert.match(practiceScript, /playExampleAudio/)
  assert.match(practiceTemplate, /wn-ex-cn/)
  assert.match(practiceTemplate, /showHint/)
})

test('认识 and 不认识 reveal the detail page after the jelly hint finishes', () => {
  assert.match(practiceScript, /answerKnow/)
  assert.match(practiceScript, /answerUnknown/)
  assert.match(practiceScript, /showWordHint\(index, 'known', \(\) => this\.revealWord/)
  assert.match(practiceScript, /WORD_HINT_VISIBLE_MS/)
  assert.match(practiceScript, /hideWordHint/)
  assert.match(practiceScript, /revealWord/)
  assert.match(practiceScript, /\.revealed'\]:\s*true/)
})

test('认识、不认识、记错了 show jelly hints beside the word instead of center toasts', () => {
  assert.match(practiceScript, /showWordHint\s*\(/)
  assert.match(practiceScript, /item\.wordHint = null/)
  assert.match(practiceScript, /item\.wordHintLabel = ''/)
  assert.match(practiceScript, /preloadWordHintImages/)
  assert.match(practiceScript, /known:\s*'继续保持'/)
  assert.match(practiceScript, /unknown:\s*'一起巩固'/)
  assert.match(practiceScript, /mistaken:\s*'记错了'/)
  assert.match(practiceScript, /showWordHint\(index, 'known', \(\) => this\.revealWord/)
  assert.match(practiceScript, /showWordHint\(index, 'unknown', \(\) => this\.revealWord/)
  assert.match(practiceScript, /this\.showWordHint\(index, 'mistaken'\)/)
  assert.match(practiceScript, /_wordHintHideTimer/)
  assert.match(practiceScript, /\.wordHint'\]:\s*null/)
  assert.match(practiceTemplate, /item\.wordHint && !item\.revealed/)
  assert.match(practiceTemplate, /item\.wordHint && item\.revealed/)
  assert.match(practiceTemplate, /class="wn-jelly-hint/)
  assert.match(practiceTemplate, /wn-jelly-hint-pop/)
  assert.doesNotMatch(practiceScript, /_wordHintAnimTimer/)
  assert.match(practiceTemplate, /word-new\/toast-\{\{item\.wordHint\}\}\.png/)
  assert.match(practiceTemplate, /wordHintLabel/)
  assert.match(practiceStyle, /\.wn-jelly-hint\s*{[^}]*flex-direction:\s*row/s)
  assert.match(practiceStyle, /\.wn-jelly-hint-img\s*{/)
  assert.match(practiceStyle, /\.wn-jelly-hint-label\s*{[^}]*font-weight:\s*400/s)
  assert.match(practiceStyle, /@keyframes wn-jelly-hint-life/)
  assert.doesNotMatch(practiceStyle, /\.wn-jelly-hint-pop \.wn-jelly-hint-label/)
  assert.doesNotMatch(practiceStyle, /\.wn-jelly-hint\s*{[^}]*background:/s)
  assert.doesNotMatch(practiceScript, /showWordDecisionToast\s*\(/)
  assert.doesNotMatch(practiceScript, /wordToast:\s*{/)
  assert.doesNotMatch(practiceTemplate, /class="wn-toast"/)
  assert.doesNotMatch(practiceStyle, /\.wn-toast\s*{/)
  assert.doesNotMatch(practiceScript, /wx\.showToast\s*\(/)
})

test('detail footer shows 记错了 only after tapping 认识', () => {
  assert.match(practiceTemplate, /记错了/)
  assert.match(practiceTemplate, /wx:if="{{item\.known}}"/)
  assert.match(practiceTemplate, /markWordMistaken/)
  assert.match(practiceScript, /markWordMistaken\s*\(/)
  assert.match(practiceScript, /\.known'\]:\s*false/)
  assert.match(practiceScript, /\.mistaken'\]:\s*true/)
  assert.doesNotMatch(practiceTemplate, /wn-correction-tip/)
  assert.doesNotMatch(practiceStyle, /\.wn-correction-tip\s*{/)
  assert.match(practiceTemplate, /wn-foot-underline-known/)
  assert.match(practiceTemplate, /wn-foot-underline-wrong/)
  assert.doesNotMatch(practiceTemplate, /wn-foot-mark/)
})

test('detail page renders data-backed sections plus 下一词', () => {
  assert.match(practiceScript, /背诵技巧/)
  assert.doesNotMatch(practiceScript, /真题例句/)
  assert.doesNotMatch(practiceTemplate, /<text class="wn-sec-name">发音技巧<\/text>/)
  assert.match(practiceTemplate, /下一词/)
  assert.match(practiceTemplate, /practice-top-progress/)
  assert.match(practiceStyle, /\.practice-top-progress\s*{/)
  assert.match(practiceScript, /getPracticeProgressPercent/)
  assert.match(practiceTemplate, /practiceProgress\.getTrackStyle\(current, wordTotal\)/)
  assert.match(practiceScript, /wordTotal/)
  assert.match(practiceTemplate, /<view class="word-new-swiper"/)
  assert.doesNotMatch(practiceTemplate, /<swiper class="word-new-swiper"/)
  assert.match(practiceScript, /const next = this\.data\.current \+ 1/)
  assert.match(practiceScript, /近义词/)
  assert.match(practiceScript, /联想记忆/)
  assert.match(practiceScript, /词根/)
  assert.doesNotMatch(practiceScript, /模拟真题/)
  assert.match(practiceScript, /normalizeWordDetail/)
  assert.match(practiceScript, /detailNavItems/)
  assert.match(practiceScript, /switchDetailTab/)
  assert.match(practiceTemplate, /item\.word\.detailNavItems/)
  assert.match(practiceTemplate, /item\.word\.activeDetailTab/)
  assert.match(practiceTemplate, /item\.word\.activeDetailTab == 'recite'/)
  assert.match(practiceScript, /先发 \/æ\/ 音/)
  assert.doesNotMatch(practiceTemplate, /switchWordDetailTab/)
  assert.doesNotMatch(practiceScript, /wordDetailTabs/)
})

test('target word in the example sentence is emphasised via a wxs helper', () => {
  assert.match(paintWxs, /markWord:/)
  assert.match(practiceTemplate, /paintHandler\.markWord/)
  assert.match(practiceTemplate, /wn-ex-bold/)
  assert.match(practiceStyle, /\.wn-word\s*{[^}]*font-weight:\s*800/s)
  assert.match(practiceStyle, /\.wn-ex-text\s*{[^}]*font-weight:\s*400/s)
  assert.match(practiceStyle, /\.wn-ex-bold\s*{[^}]*font-weight:\s*800/s)
  assert.match(paintWxs, /markerReg/)
  assert.match(paintWxs, /markCleanWordToken/)
  assert.match(markWordBlock, /targetMap\[core\]/)
  assert.doesNotMatch(markWordBlock, /item\.search\(reg2\)/)
})

test('word-new detail styling follows the lavender-blue "认识不" visual language', () => {
  assert.match(practiceStyle, /#dfd8ee/)
  assert.match(practiceStyle, /#ddddf7/)
  assert.match(practiceStyle, /#8bb6fa/)
  assert.match(practiceStyle, /\.wn-word\s*{[^}]*font-weight:\s*800/s)
  assert.match(practiceStyle, /\.wn-foot-underline-img\s*{/)
  assert.match(practiceStyle, /\.wn-foot-underline-known\s*{[^}]*background:\s*#3f9581/s)
  assert.match(practiceStyle, /\.wn-foot-underline-wrong\s*{[^}]*background:\s*#fb5632/s)
  assert.match(practiceStyle, /\.wn-bar\s*{/)
  assert.match(practiceStyle, /\.wn-card\s*{/)
})

test('masked definition placeholders look like soft frosted overlays', () => {
  assert.match(practiceStyle, /\.wn-bars\s*{[^}]*gap:\s*18rpx/s)
  assert.match(practiceStyle, /\.wn-bar\s*{[^}]*height:\s*46rpx/s)
  assert.match(practiceStyle, /\.wn-bar\s*{[^}]*rgba\(255,\s*255,\s*255,\s*0\.34\)/s)
  assert.match(practiceStyle, /\.wn-bar\s*{[^}]*backdrop-filter:\s*blur\(18rpx\)/s)
  assert.match(practiceStyle, /\.wn-bar-1\s*{[^}]*width:\s*42%/s)
  assert.match(practiceStyle, /\.wn-bar-2\s*{[^}]*width:\s*34%/s)
})

test('word-new quiz layout matches the reference learning card composition', () => {
  assert.match(practiceStyle, /\.wn-quiz-body\s*{[^}]*padding:\s*42rpx 54rpx 0/s)
  assert.match(practiceStyle, /\.wn-word\s*{[^}]*font-size:\s*70rpx/s)
  assert.match(practiceStyle, /\.wn-ex-text\s*{[^}]*font-size:\s*34rpx/s)
  assert.match(practiceStyle, /\.wn-example\s*{[^}]*margin-top:\s*64rpx/s)
  assert.match(practiceStyle, /\.wn-example\s*{[^}]*min-height:\s*292rpx/s)
  assert.match(practiceStyle, /\.wn-card\s*{[^}]*border-radius:\s*40rpx/s)
  assert.match(practiceStyle, /\.wn-hint\s*{[^}]*padding-bottom:\s*126rpx/s)
  assert.match(practiceStyle, /\.wn-quiz-foot\s*{[^}]*padding-top:\s*10rpx/s)
})

test('word-new pronunciation row exposes British and American accents', () => {
  assert.match(practiceScript, /normalizeWordPronunciations/)
  assert.match(practiceScript, /label:\s*'英'/)
  assert.match(practiceScript, /label:\s*'美'/)
  assert.match(practiceTemplate, /item\.word\.pronunciations/)
  assert.match(practiceTemplate, /switchWordAccent/)
})

test('hint bulb uses the word-new image asset instead of css drawing', () => {
  assert.match(practiceTemplate, /word-new\/hint-bulb\.png/)
  assert.match(practiceStyle, /\.wn-hint-btn\s*{[^}]*width:\s*108rpx/s)
  assert.match(practiceStyle, /\.wn-hint-icon\s*{[^}]*width:\s*66rpx/s)
  assert.match(practiceStyle, /\.wn-hint\s*{[^}]*padding-bottom:\s*126rpx/s)
  assert.match(practiceStyle, /\.wn-hint-label\s*{[^}]*margin-top:\s*32rpx/s)
  assert.match(practiceStyle, /\.wn-hint-label\s*{[^}]*font-size:\s*26rpx/s)
  assert.match(practiceStyle, /\.wn-hint-label\s*{[^}]*#3a505f/s)
  assert.doesNotMatch(practiceTemplate, /wn-bulb-head/)
  assert.doesNotMatch(practiceTemplate, /wn-bulb-stem/)
})
