const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const projectRoot = path.resolve(__dirname, '..')
const practiceScript = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.js'), 'utf8')
const practiceTemplate = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.wxml'), 'utf8')
const practiceStyle = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.wxss'), 'utf8')
const paintWxs = fs.readFileSync(path.join(projectRoot, 'pages/paint.wxs'), 'utf8')

test('practice page exposes a word-new mode driven by the task type route option', () => {
  assert.match(practiceScript, /taskType:\s*'recitation'/)
  assert.match(practiceScript, /isWordNewMode/)
  assert.match(practiceScript, /options\.taskType === 'word'/)
})

test('word-new starts each card in an unrevealed "认识不" quiz state', () => {
  assert.match(practiceScript, /item\.revealed = false/)
  assert.match(practiceScript, /item\.hinted = false/)
  assert.match(practiceScript, /item\.mistaken = false/)
  assert.match(practiceTemplate, /wx:if="{{!item\.revealed}}"/)
  assert.match(practiceTemplate, /提示一下/)
  assert.match(practiceTemplate, /认识/)
  assert.match(practiceTemplate, /不认识/)
})

test('word-new audio progress uses the three dots as one-time stage markers', () => {
  assert.match(practiceScript, /三个点分别对应：问答页读词、详情页读词、详情页读例句/)
  assert.match(practiceScript, /startWordReading\s*\(index\)/)
  assert.match(practiceScript, /\['contents\[' \+ index \+ '\]\.readCount'\]: 1/)
  assert.doesNotMatch(practiceScript, /count < 3/)
  assert.match(practiceScript, /playDetailIntro\s*\(index\)/)
  assert.match(practiceScript, /setWordReadCount\(index, 2\)/)
  assert.match(practiceScript, /setWordReadCount\(index, 3\)/)
  assert.match(practiceScript, /getExampleAudio\s*\(index\)/)
  assert.match(practiceTemplate, /item\.readCount >= 1/)
  assert.match(practiceTemplate, /item\.readCount >= 2/)
  assert.match(practiceTemplate, /item\.readCount >= 3/)
  assert.doesNotMatch(practiceTemplate, /<view class="wn-dots"><view class="wn-dot-on"><\/view><view class="wn-dot-on"><\/view><view class="wn-dot-on"><\/view><\/view>/)
})

test('提示一下 reveals the example translation and plays its audio without revealing the card', () => {
  assert.match(practiceScript, /showHint\s*\(/)
  assert.match(practiceScript, /playExampleAudio/)
  assert.match(practiceTemplate, /wn-ex-cn/)
  assert.match(practiceTemplate, /showHint/)
})

test('认识 and 不认识 both reveal the detail page', () => {
  assert.match(practiceScript, /answerKnow/)
  assert.match(practiceScript, /answerUnknown/)
  assert.match(practiceScript, /revealWord/)
  assert.match(practiceScript, /\.revealed'\]:\s*true/)
})

test('认识、不认识、记错了 all show weak image toasts', () => {
  assert.match(practiceScript, /showWordDecisionToast\s*\(/)
  assert.match(practiceScript, /wordToast:\s*{/)
  assert.match(practiceScript, /title:\s*'继续保持'/)
  assert.match(practiceScript, /title:\s*'一起巩固'/)
  assert.match(practiceScript, /title:\s*'已改为不认识'/)
  assert.match(practiceScript, /image:\s*'\.\.\/\.\.\/images\/word-new\/toast-known\.png'/)
  assert.match(practiceScript, /image:\s*'\.\.\/\.\.\/images\/word-new\/toast-unknown\.png'/)
  assert.match(practiceScript, /image:\s*'\.\.\/\.\.\/images\/word-new\/toast-mistaken\.png'/)
  assert.match(practiceScript, /this\.showWordDecisionToast\('known'\)/)
  assert.match(practiceScript, /this\.showWordDecisionToast\('unknown'\)/)
  assert.match(practiceScript, /this\.showWordDecisionToast\('mistaken'\)/)
  assert.match(practiceTemplate, /wx:if="{{wordToast\.visible}}"/)
  assert.match(practiceTemplate, /class="wn-toast"/)
  assert.match(practiceTemplate, /wordToast\.image/)
  assert.match(practiceTemplate, /wordToast\.title/)
  assert.match(practiceStyle, /\.wn-toast\s*{/)
  assert.match(practiceStyle, /\.wn-toast\s*{[^}]*top:\s*50%/s)
  assert.match(practiceStyle, /\.wn-toast\s*{[^}]*transform:\s*translate\(-50%,\s*-50%\)/s)
  assert.match(practiceStyle, /\.wn-toast-image\s*{/)
  assert.match(practiceStyle, /\.wn-toast-title\s*{/)
  assert.doesNotMatch(practiceScript, /wx\.showToast\s*\(/)
})

test('detail footer shows 记错了 only after tapping 认识', () => {
  assert.match(practiceTemplate, /记错了/)
  assert.match(practiceTemplate, /wx:if="{{item\.known}}"/)
  assert.match(practiceTemplate, /markWordMistaken/)
  assert.match(practiceScript, /markWordMistaken\s*\(/)
  assert.match(practiceScript, /\.known'\]:\s*false/)
  assert.match(practiceScript, /\.mistaken'\]:\s*true/)
  assert.doesNotMatch(practiceTemplate, /wn-correction-tip/)
  assert.doesNotMatch(practiceStyle, /\.wn-correction-tip\s*{/)
  assert.match(practiceTemplate, /wn-foot-underline-known/)
  assert.match(practiceTemplate, /wn-foot-underline-wrong/)
  assert.doesNotMatch(practiceTemplate, /wn-foot-mark/)
})

test('detail page renders data-backed sections plus 下一词', () => {
  assert.match(practiceScript, /背诵技巧/)
  assert.doesNotMatch(practiceScript, /真题例句/)
  assert.doesNotMatch(practiceTemplate, /<text class="wn-sec-name">发音技巧<\/text>/)
  assert.match(practiceTemplate, /下一词/)
  assert.match(practiceTemplate, /practice-top-progress/)
  assert.match(practiceStyle, /\.practice-top-progress\s*{/)
  assert.match(practiceScript, /getPracticeProgressPercent/)
  assert.match(practiceScript, /buildPracticeProgress/)
  assert.match(practiceScript, /practiceProgressWidth/)
  assert.match(practiceTemplate, /practiceProgressWidth/)
  assert.match(practiceTemplate, /<view class="word-new-swiper"/)
  assert.doesNotMatch(practiceTemplate, /<swiper class="word-new-swiper"/)
  assert.match(practiceScript, /const next = this\.data\.current \+ 1/)
  assert.match(practiceScript, /近义词/)
  assert.match(practiceScript, /联想记忆/)
  assert.match(practiceScript, /词根/)
  assert.doesNotMatch(practiceScript, /模拟真题/)
  assert.match(practiceScript, /normalizeWordDetail/)
  assert.match(practiceScript, /detailNavItems/)
  assert.match(practiceScript, /switchDetailTab/)
  assert.match(practiceTemplate, /item\.word\.detailNavItems/)
  assert.match(practiceTemplate, /item\.word\.activeDetailTab/)
  assert.match(practiceTemplate, /item\.word\.activeDetailTab == 'recite'/)
  assert.match(practiceScript, /先发 \/æ\/ 音/)
  assert.doesNotMatch(practiceTemplate, /switchWordDetailTab/)
  assert.doesNotMatch(practiceScript, /wordDetailTabs/)
})

test('target word in the example sentence is emphasised via a wxs helper', () => {
  assert.match(paintWxs, /markWord:/)
  assert.match(practiceTemplate, /paintHandler\.markWord/)
  assert.match(practiceTemplate, /wn-ex-bold/)
  assert.match(practiceStyle, /\.wn-word\s*{[^}]*font-weight:\s*800/s)
  assert.match(practiceStyle, /\.wn-ex-text\s*{[^}]*font-weight:\s*400/s)
  assert.match(practiceStyle, /\.wn-ex-bold\s*{[^}]*font-weight:\s*900/s)
  assert.match(paintWxs, /markerReg/)
  assert.match(paintWxs, /markCleanWordToken/)
})

test('word-new detail styling follows the lavender-blue "认识不" visual language', () => {
  assert.match(practiceStyle, /\.wn-bg\s*{[^}]*linear-gradient/s)
  assert.match(practiceStyle, /\.wn-word\s*{[^}]*font-weight:\s*800/s)
  assert.match(practiceStyle, /#ece6f0/)
  assert.match(practiceStyle, /#5fa9f7/)
  assert.match(practiceStyle, /\.wn-foot-underline-img\s*{/)
  assert.match(practiceStyle, /\.wn-foot-underline-known\s*{[^}]*background:\s*#3f9581/s)
  assert.match(practiceStyle, /\.wn-foot-underline-wrong\s*{[^}]*background:\s*#fb5632/s)
  assert.match(practiceStyle, /\.wn-bar\s*{/)
  assert.match(practiceStyle, /\.wn-card\s*{/)
})

test('word-new pronunciation row exposes British and American accents', () => {
  assert.match(practiceScript, /normalizeWordPronunciations/)
  assert.match(practiceScript, /label:\s*'英'/)
  assert.match(practiceScript, /label:\s*'美'/)
  assert.match(practiceTemplate, /item\.word\.pronunciations/)
  assert.match(practiceTemplate, /switchWordAccent/)
})

test('hint bulb uses the word-new image asset instead of css drawing', () => {
  assert.match(practiceTemplate, /word-new\/hint-bulb\.png/)
  assert.match(practiceStyle, /\.wn-hint-btn\s*{[^}]*width:\s*108rpx/s)
  assert.match(practiceStyle, /\.wn-hint-icon\s*{[^}]*width:\s*58rpx/s)
  assert.match(practiceStyle, /\.wn-hint\s*{[^}]*padding-bottom:\s*150rpx/s)
  assert.match(practiceStyle, /\.wn-hint-label\s*{[^}]*margin-top:\s*32rpx/s)
  assert.match(practiceStyle, /\.wn-hint-label\s*{[^}]*font-size:\s*26rpx/s)
  assert.match(practiceStyle, /\.wn-hint-label\s*{[^}]*#3a505f/s)
  assert.doesNotMatch(practiceTemplate, /wn-bulb-head/)
  assert.doesNotMatch(practiceTemplate, /wn-bulb-stem/)
})
