const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const projectRoot = path.resolve(__dirname, '..')
const practiceScript = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.js'), 'utf8')
const practiceTemplate = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.wxml'), 'utf8')
const practiceStyle = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.wxss'), 'utf8')
const paintWxs = fs.readFileSync(path.join(projectRoot, 'pages/paint.wxs'), 'utf8')
const markWordBlock = paintWxs.slice(paintWxs.indexOf('markWord:'))

test('practice page exposes a word-new mode driven by the task type route option', () => {
  assert.match(practiceScript, /taskType:\s*'recitation'/)
  assert.match(practiceScript, /isWordNewMode/)
  assert.match(practiceScript, /options\.taskType === 'word'/)
})

test('word-new starts each card in an unrevealed "认识不" quiz state', () => {
  assert.match(practiceScript, /item\.revealed = false/)
  assert.match(practiceScript, /item\.wordNewStage = 'recognition'/)
  assert.match(practiceScript, /item\.hinted = false/)
  assert.match(practiceScript, /item\.mistaken = false/)
  assert.match(practiceTemplate, /wx:if="{{item\.wordNewStage == 'recognition'}}"/)
  assert.match(practiceTemplate, /提示一下/)
  assert.match(practiceTemplate, /<text class="wn-foot-text">认识<\/text>/)
  assert.match(practiceTemplate, /<text class="wn-foot-text">不认识<\/text>/)
  assert.doesNotMatch(practiceTemplate, /wn-answer-known/)
  assert.doesNotMatch(practiceTemplate, /wn-answer-unknown/)
})

test('word-new known and unknown answers route through the choice quiz flow', () => {
  assert.match(practiceScript, /buildWordChoiceOptions/)
  assert.match(practiceScript, /wordNewStage/)
  assert.match(practiceScript, /wordChoiceOrigin/)
  assert.match(practiceScript, /answerKnow\s*\(\)\s*{[\s\S]*enterWordChoice\(index, 'known'\)/)
  assert.match(practiceScript, /answerUnknown\s*\(\)\s*{[\s\S]*enterWordDetail\(index, 'unknown'\)/)
  assert.match(practiceScript, /continueFromWordDetail\s*\(\)/)
  assert.match(practiceScript, /enterWordChoice\(index, 'unknown'\)/)
  assert.match(practiceScript, /selectWordChoice\s*\(/)
  assert.match(practiceScript, /wordChoiceSelectedIndex/)
  assert.match(practiceScript, /wordChoiceCorrect/)
  assert.match(practiceScript, /continueUnderstandWord\s*\(\)/)
  assert.match(practiceScript, /enterWordDetail\(index, 'choice'\)/)
  assert.match(practiceTemplate, /item\.wordNewStage == 'choice'/)
  assert.match(practiceTemplate, /item\.wordNewStage == 'detail'/)
  assert.match(practiceTemplate, /先回想词义再选择，想不起来「看答案」/)
  assert.match(practiceTemplate, /selectWordChoice/)
  assert.match(practiceTemplate, /item\.wordChoiceSelectedIndex != null/)
  assert.match(practiceTemplate, /继续了解/)
  assert.match(practiceTemplate, /continueFromWordDetail/)
  assert.match(practiceTemplate, /continueUnderstandWord/)
  assert.match(practiceTemplate, /wordChoiceOrigin == 'known' && item\.wordChoiceCorrect/)
  assert.match(practiceTemplate, /wordChoiceOrigin == 'known' && !item\.wordChoiceCorrect/)
})

test('word-new quiz and choice stages keep their content vertically scrollable on tall tablets', () => {
  assert.match(practiceTemplate, /<scroll-view scroll-y class="word-new-stage-scroll word-new-recognition-scroll" enhanced show-scrollbar="{{false}}">/)
  assert.match(practiceTemplate, /<scroll-view scroll-y class="word-new-stage-scroll word-new-choice-scroll" enhanced show-scrollbar="{{false}}">/)
  assert.match(practiceTemplate, /class="wn-quiz-foot" style="padding-bottom: {{safeAreaBottom \+ 48}}px;"/)
  assert.match(practiceTemplate, /class="wn-quiz-foot wn-choice-foot" style="padding-bottom: {{safeAreaBottom \+ 48}}px;"/)
  assert.match(practiceTemplate, /class="wn-detail-foot wn-detail-foot-single" style="padding-bottom: {{safeAreaBottom \+ 48}}px;"/)
  assert.match(practiceStyle, /\.word-new-stage-scroll\s*{[^}]*flex:\s*1/s)
  assert.match(practiceStyle, /\.word-new-stage-scroll\s*{[^}]*min-height:\s*0/s)
  assert.match(practiceStyle, /\.word-new-stage-scroll\s*{[^}]*box-sizing:\s*border-box/s)
  assert.match(practiceStyle, /\.wn-quiz-body\s*{[^}]*min-height:\s*100%/s)
  assert.match(practiceStyle, /\.wn-choice-stage\s*{[^}]*min-height:\s*100%/s)
  assert.doesNotMatch(practiceStyle, /\.wn-quiz-body\s*{[^}]*overflow:\s*hidden/s)
  assert.doesNotMatch(practiceStyle, /\.wn-choice-stage\s*{[^}]*overflow:\s*hidden/s)
})

test('word choice options reveal every matching word and keep two-line meanings after selection', () => {
  assert.match(practiceTemplate, /class="wn-choice-word-row"/)
  assert.match(practiceTemplate, /wx:if="{{item\.wordChoiceSelectedIndex != null}}" class="wn-choice-word"/)
  assert.match(practiceTemplate, /wx:else class="wn-choice-pos wn-choice-pos-text"/)
  assert.doesNotMatch(practiceTemplate, /item\.wordChoiceSelectedIndex != null && \(option\.isAnswer \|\| item\.wordChoiceSelectedIndex == optionIndex\)/)
  assert.match(practiceTemplate, /wx:if="{{option\.audio && playingSrc && playingSrc == option\.audio}}" class="wn-choice-audio"/)
  assert.match(practiceScript, /audio:\s*word\.audio \|\| word\.ukAudio \|\| word\.enAudio \|\| ''/)
  assert.match(practiceTemplate, /wn-choice-pos-text/)
  assert.match(practiceTemplate, /wn-choice-term-text/)
  assert.match(practiceTemplate, /{{option\.termText}}/)
})

test('word-new audio progress uses the three dots as one-time stage markers', () => {
  assert.match(practiceScript, /三个点分别对应：问答页读词、详情页读词、详情页读例句/)
  assert.match(practiceScript, /startWordReading\s*\(index\)/)
  assert.match(practiceScript, /\['contents\[' \+ index \+ '\]\.readCount'\]: 1/)
  assert.doesNotMatch(practiceScript, /count < 3/)
  assert.match(practiceScript, /playDetailIntro\s*\(index\)/)
  assert.match(practiceScript, /setWordReadCount\(index, 2\)/)
  assert.match(practiceScript, /setWordReadCount\(index, 3\)/)
  assert.match(practiceScript, /getExampleAudio\s*\(index\)/)
  assert.match(practiceTemplate, /item\.readCount >= 1/)
  assert.match(practiceTemplate, /item\.readCount >= 2/)
  assert.match(practiceTemplate, /item\.readCount >= 3/)
  assert.doesNotMatch(practiceTemplate, /<view class="wn-dots"><view class="wn-dot-on"><\/view><view class="wn-dot-on"><\/view><view class="wn-dot-on"><\/view><\/view>/)
})

test('提示一下 reveals the example translation and plays its audio without revealing the card', () => {
  assert.match(practiceScript, /showHint\s*\(/)
  assert.match(practiceScript, /playExampleAudio/)
  assert.match(practiceTemplate, /wn-ex-cn/)
  assert.match(practiceTemplate, /showHint/)
})

test('认识 starts the choice quiz and 不认识 opens detail before testing', () => {
  assert.match(practiceScript, /answerKnow/)
  assert.match(practiceScript, /answerUnknown/)
  assert.match(practiceScript, /this\.enterWordChoice\(index, 'known'\)/)
  assert.match(practiceScript, /this\.enterWordDetail\(index, 'unknown'\)/)
  assert.doesNotMatch(practiceScript, /showWordHint\(index, 'known', \(\) => this\.revealWord/)
  assert.doesNotMatch(practiceScript, /showWordHint\(index, 'unknown', \(\) => this\.revealWord/)
  assert.match(practiceScript, /\.revealed'\]:\s*true/)
})

test('word-new inline jelly hints remain available for correction feedback only', () => {
  assert.match(practiceScript, /showWordHint\s*\(/)
  assert.match(practiceScript, /item\.wordHint = null/)
  assert.match(practiceScript, /item\.wordHintLabel = ''/)
  assert.match(practiceScript, /preloadWordHintImages/)
  assert.match(practiceScript, /mistaken:\s*'记错了'/)
  assert.doesNotMatch(practiceScript, /showWordHint\(index, 'known', \(\) => this\.revealWord/)
  assert.doesNotMatch(practiceScript, /showWordHint\(index, 'unknown', \(\) => this\.revealWord/)
  assert.match(practiceScript, /this\.showWordHint\(index, 'mistaken'\)/)
  assert.match(practiceScript, /_wordHintHideTimer/)
  assert.match(practiceScript, /\.wordHint'\]:\s*null/)
  assert.match(practiceTemplate, /item\.wordHint && !item\.revealed/)
  assert.match(practiceTemplate, /item\.wordHint && item\.revealed/)
  assert.match(practiceTemplate, /class="wn-jelly-hint/)
  assert.match(practiceTemplate, /wn-jelly-hint-pop/)
  assert.doesNotMatch(practiceScript, /_wordHintAnimTimer/)
  assert.match(practiceTemplate, /word-new\/toast-\{\{item\.wordHint\}\}\.png/)
  assert.match(practiceTemplate, /wordHintLabel/)
  assert.match(practiceStyle, /\.wn-jelly-hint\s*{[^}]*flex-direction:\s*row/s)
  assert.match(practiceStyle, /\.wn-jelly-hint-img\s*{/)
  assert.match(practiceStyle, /\.wn-jelly-hint-label\s*{[^}]*font-weight:\s*400/s)
  assert.match(practiceStyle, /@keyframes wn-jelly-hint-life/)
  assert.doesNotMatch(practiceStyle, /\.wn-jelly-hint-pop \.wn-jelly-hint-label/)
  assert.doesNotMatch(practiceStyle, /\.wn-jelly-hint\s*{[^}]*background:/s)
  assert.doesNotMatch(practiceScript, /showWordDecisionToast\s*\(/)
  assert.doesNotMatch(practiceScript, /wordToast:\s*{/)
  assert.doesNotMatch(practiceTemplate, /class="wn-toast"/)
  assert.doesNotMatch(practiceStyle, /\.wn-toast\s*{/)
  assert.doesNotMatch(practiceScript, /wx\.showToast\s*\(/)
})

test('detail footer shows 继续 before unknown-path test and 下一词 afterward', () => {
  assert.doesNotMatch(practiceTemplate, /记错了/)
  assert.doesNotMatch(practiceTemplate, /markWordMistaken/)
  assert.match(practiceTemplate, /continueFromWordDetail/)
  assert.match(practiceTemplate, /item\.wordChoiceOrigin == 'unknown' && item\.wordChoiceSelectedIndex == null/)
  assert.match(practiceTemplate, /<text class="wn-next">继续<\/text>/)
  assert.match(practiceTemplate, /<text class="wn-next">\{\{current >= contents\.length - 1 \? '提交' : '下一词'\}\}<\/text>/)
  assert.match(practiceScript, /\.known'\]:\s*false/)
  assert.match(practiceScript, /\.mistaken'\]:\s*true/)
  assert.doesNotMatch(practiceTemplate, /wn-correction-tip/)
  assert.doesNotMatch(practiceStyle, /\.wn-correction-tip\s*{/)
  assert.match(practiceTemplate, /wn-foot-underline-known/)
  assert.match(practiceTemplate, /wn-foot-underline-wrong/)
  assert.doesNotMatch(practiceTemplate, /wn-foot-mark/)
})

test('word row shows a persistent status mark after an answer', () => {
  assert.doesNotMatch(practiceTemplate, /mark-familiar\.png/)
  assert.doesNotMatch(practiceTemplate, /mark-unknown\.png/)
  assert.match(practiceTemplate, /item\.revealed && item\.known/)
  assert.match(practiceTemplate, /item\.revealed && !item\.known/)
  assert.match(practiceTemplate, /<text class="wn-word">\{\{item\.word\.content\}\}<\/text>[\s\S]*<view class="wn-dots">[\s\S]*wn-word-status-known/)
  assert.match(practiceStyle, /\.wn-word-status\s*{/)
  assert.match(practiceTemplate, /class="wn-word-status wn-word-status-known"/)
  assert.match(practiceTemplate, /class="wn-word-status wn-word-status-unknown"/)
  assert.match(practiceStyle, /\.wn-word-status\s*{[^}]*width:\s*38rpx/s)
  assert.match(practiceStyle, /\.wn-word-status\s*{[^}]*margin-left:\s*-4rpx/s)
  assert.match(practiceStyle, /\.wn-word-status\s*{[^}]*transform:\s*translateY\(-18rpx\)/s)
  assert.match(practiceStyle, /\.wn-word-status-known\s*{[^}]*#58c98e/s)
  assert.match(practiceStyle, /\.wn-word-status-unknown\s*{[^}]*#ffe2d3/s)
  assert.match(practiceTemplate, /wn-word-status-check/)
  assert.match(practiceTemplate, /wn-word-status-bang-line/)
  assert.match(practiceTemplate, /wn-word-status-bang-dot/)
})

test('detail page renders data-backed sections plus 下一词', () => {
  assert.match(practiceScript, /背诵技巧/)
  assert.doesNotMatch(practiceScript, /真题例句/)
  assert.doesNotMatch(practiceTemplate, /<text class="wn-sec-name">发音技巧<\/text>/)
  assert.match(practiceTemplate, /下一词/)
  assert.match(practiceTemplate, /practice-top-progress/)
  assert.match(practiceStyle, /\.practice-top-progress\s*{/)
  assert.match(practiceScript, /getPracticeProgressPercent/)
  assert.match(practiceTemplate, /practiceProgress\.getTrackStyle\(current, wordTotal\)/)
  assert.match(practiceScript, /wordTotal/)
  assert.match(practiceTemplate, /<view class="word-new-swiper"/)
  assert.doesNotMatch(practiceTemplate, /<swiper class="word-new-swiper"/)
  assert.match(practiceScript, /const next = this\.data\.current \+ 1/)
  assert.match(practiceScript, /近义词/)
  assert.match(practiceScript, /英译英/)
  assert.match(practiceScript, /联想记忆/)
  assert.match(practiceScript, /词根/)
  assert.doesNotMatch(practiceScript, /模拟真题/)
  assert.match(practiceScript, /normalizeWordDetail/)
  assert.match(practiceScript, /detailNavItems/)
  assert.match(practiceScript, /switchDetailTab/)
  assert.match(practiceTemplate, /item\.word\.detailNavItems/)
  assert.match(practiceTemplate, /item\.word\.activeDetailTab/)
  assert.match(practiceTemplate, /item\.word\.activeDetailTab == 'enEn'/)
  assert.match(practiceTemplate, /item\.word\.activeDetailTab == 'recite'/)
  assert.match(practiceTemplate, /item\.word\.enEnDetail/)
  assert.match(practiceScript, /先发 \/æ\/ 音/)
  assert.doesNotMatch(practiceTemplate, /switchWordDetailTab/)
  assert.doesNotMatch(practiceScript, /wordDetailTabs/)
})

test('proverb recitation keeps English label visible after scoring', () => {
  assert.match(practiceTemplate, /proverb\.result\.detail,item\.word\.exchange,item\.word\.content,proverb\.result\.score/)
  assert.match(practiceTemplate, /refText:proverb\.refText \|\| proverb\.content/)
  assert.match(practiceScript, /normalizeProverb/)
  assert.match(paintWxs, /resolveColor/)
  assert.match(paintWxs, /detailItem && detailItem\.score != undefined/)
  assert.doesNotMatch(paintWxs, /detail\[index - spacesCount\]\.score/)
})

test('target word in the example sentence is emphasised via a wxs helper', () => {
  assert.match(paintWxs, /markWord:/)
  assert.match(practiceTemplate, /paintHandler\.markWord/)
  assert.match(practiceTemplate, /wn-ex-bold/)
  assert.match(practiceStyle, /\.wn-word\s*{[^}]*font-weight:\s*800/s)
  assert.match(practiceStyle, /\.wn-ex-text\s*{[^}]*font-weight:\s*400/s)
  assert.match(practiceStyle, /\.wn-ex-bold\s*{[^}]*font-weight:\s*800/s)
  assert.match(paintWxs, /markerReg/)
  assert.match(paintWxs, /markCleanWordToken/)
  assert.match(markWordBlock, /targetMap\[core\]/)
  assert.doesNotMatch(markWordBlock, /item\.search\(reg2\)/)
})

test('word-new detail styling follows the lavender-blue "认识不" visual language', () => {
  assert.match(practiceStyle, /#e7e1f0/)
  assert.match(practiceStyle, /#bcd0f8/)
  assert.match(practiceStyle, /#78acf4/)
  assert.match(practiceStyle, /\.wn-word\s*{[^}]*font-weight:\s*800/s)
  assert.match(practiceStyle, /\.wn-foot-underline-img\s*{/)
  assert.match(practiceStyle, /\.wn-foot-underline-known\s*{[^}]*background:\s*#3f9581/s)
  assert.match(practiceStyle, /\.wn-foot-underline-wrong\s*{[^}]*background:\s*#fb5632/s)
  assert.match(practiceStyle, /\.wn-bar\s*{/)
  assert.match(practiceStyle, /\.wn-card\s*{/)
})

test('masked definition placeholders look like soft frosted overlays', () => {
  assert.match(practiceStyle, /\.wn-bars\s*{[^}]*gap:\s*18rpx/s)
  assert.match(practiceStyle, /\.wn-bar\s*{[^}]*height:\s*46rpx/s)
  assert.match(practiceStyle, /\.wn-bar\s*{[^}]*rgba\(255,\s*255,\s*255,\s*0\.34\)/s)
  assert.match(practiceStyle, /\.wn-bar\s*{[^}]*backdrop-filter:\s*blur\(18rpx\)/s)
  assert.match(practiceStyle, /\.wn-bar-1\s*{[^}]*width:\s*42%/s)
  assert.match(practiceStyle, /\.wn-bar-2\s*{[^}]*width:\s*34%/s)
})

test('word-new quiz layout matches the reference learning card composition', () => {
  assert.match(practiceStyle, /\.wn-quiz-body\s*{[^}]*padding:\s*50rpx 54rpx 0/s)
  assert.match(practiceStyle, /\.word-new-scroll\s*{[^}]*padding:\s*50rpx 54rpx 0/s)
  assert.match(practiceStyle, /\.wn-word\s*{[^}]*font-size:\s*70rpx/s)
  assert.match(practiceStyle, /\.wn-ex-text\s*{[^}]*font-size:\s*34rpx/s)
  assert.match(practiceStyle, /\.wn-example\s*{[^}]*margin-top:\s*64rpx/s)
  assert.match(practiceStyle, /\.wn-example\s*{[^}]*min-height:\s*292rpx/s)
  assert.match(practiceStyle, /\.wn-card\s*{[^}]*border-radius:\s*40rpx/s)
  assert.match(practiceStyle, /\.wn-hint\s*{[^}]*padding-bottom:\s*126rpx/s)
  assert.match(practiceStyle, /\.wn-quiz-foot\s*{[^}]*padding-top:\s*8rpx/s)
})

test('word-new pronunciation row exposes British and American accents', () => {
  assert.match(practiceScript, /normalizeWordPronunciations/)
  assert.match(practiceScript, /label:\s*'英'/)
  assert.match(practiceScript, /label:\s*'美'/)
  assert.match(practiceTemplate, /item\.word\.pronunciations/)
  assert.match(practiceTemplate, /switchWordAccent/)
})

test('hint bulb uses the word-new image asset instead of css drawing', () => {
  assert.match(practiceTemplate, /word-new\/hint-bulb\.png/)
  assert.match(practiceStyle, /\.wn-hint-btn\s*{[^}]*width:\s*108rpx/s)
  assert.match(practiceStyle, /\.wn-hint-icon\s*{[^}]*width:\s*66rpx/s)
  assert.match(practiceStyle, /\.wn-hint\s*{[^}]*padding-bottom:\s*126rpx/s)
  assert.match(practiceStyle, /\.wn-hint-label\s*{[^}]*margin-top:\s*32rpx/s)
  assert.match(practiceStyle, /\.wn-hint-label\s*{[^}]*font-size:\s*26rpx/s)
  assert.match(practiceStyle, /\.wn-hint-label\s*{[^}]*#3a505f/s)
  assert.doesNotMatch(practiceTemplate, /wn-bulb-head/)
  assert.doesNotMatch(practiceTemplate, /wn-bulb-stem/)
})
