const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const projectRoot = path.resolve(__dirname, '..')
const practiceTemplate = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.wxml'), 'utf8')
const practiceStyle = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.wxss'), 'utf8')
const practiceConfig = fs.readFileSync(path.join(projectRoot, 'pages/practice/practice.json'), 'utf8')

test('practice page uses native image speaker buttons in pronunciation pills', () => {
  assert.match(practiceTemplate, /class="wn-spk/)
  assert.match(practiceTemplate, /class="wn-ex-spk-img/)
  assert.match(practiceTemplate, /images\/audio_small_hint\.png/)
  assert.match(practiceTemplate, /images\/audio_small_white\.png/)
  assert.doesNotMatch(practiceTemplate, /sound-wave-icon/)
  assert.doesNotMatch(practiceConfig, /sound-wave-icon/)
  assert.match(practiceStyle, /\.wn-pron-active \.wn-pron-pill\s*{[^}]*background:\s*#4b4c5a/s)
  assert.match(practiceStyle, /\.wn-pron-pill\s*{[^}]*height:\s*54rpx/s)
  assert.match(practiceStyle, /\.wn-pron-pill\s*{[^}]*rgba\(255,\s*255,\s*255,\s*0\.76\)/s)
  assert.match(practiceStyle, /\.wn-spk\s*{[^}]*width:\s*28rpx/s)
  assert.match(practiceStyle, /\.wn-spk\s*{[^}]*opacity:\s*0\.82/s)
  assert.match(practiceStyle, /\.wn-pron-active \.wn-spk\s*{[^}]*opacity:\s*0\.96/s)
  assert.match(practiceStyle, /\.wn-ex-spk-img\s*{[^}]*width:\s*38rpx/s)
  assert.match(practiceStyle, /@keyframes wn-spk-pulse/)
  assert.doesNotMatch(practiceStyle, /\.wn-ex-spk\s*{[^}]*background:/s)
  assert.doesNotMatch(practiceStyle, /\.wn-ex-spk\s*{[^}]*border-radius:/s)
  assert.doesNotMatch(practiceStyle, /\.wn-ex-spk\s*{[^}]*box-shadow:/s)
  assert.match(practiceStyle, /\.wn-ex-block\s*{/)
  assert.match(practiceStyle, /\.wn-ex-cn\s*{[^}]*text-align:\s*left/s)
  assert.ok(fs.existsSync(path.join(projectRoot, 'images/audio_small_hint.png')))
  assert.ok(fs.existsSync(path.join(projectRoot, 'images/audio_small_white.png')))
})
