module.exports = [
  ['Learn a little every day.', '每天学一点。'],
  ['A curious mind is never empty.', '好奇的心永远不会空虚。'],
  ['Questions open the door to knowledge.', '问题会打开知识之门。'],
  ['Practice turns knowledge into skill.', '练习让知识变成技能。'],
  ['Every lesson begins with attention.', '每一课都始于专注。'],
  ['Read widely and think deeply.', '广泛阅读，深入思考。'],
  ['Mistakes are lessons in disguise.', '错误是藏起来的课程。'],
  ['Understanding grows through use.', '理解在运用中增长。'],
  ['Knowledge becomes power when applied.', '知识在应用时才成为力量。'],
  ['The more you learn, the more you see.', '学得越多，看得越远。'],
  ['A good question is half an answer.', '好问题就是答案的一半。'],
  ['Study today and shine tomorrow.', '今日勤学，明日闪耀。'],
  ['Learning is a journey without an end.', '学习是一场没有终点的旅程。'],
  ['New words build new worlds.', '新词汇构建新世界。'],
  ['Listen carefully before you speak.', '开口之前先认真倾听。'],
  ['Review makes memory stronger.', '复习让记忆更牢固。'],
  ['Teach what you want to remember.', '想记得更牢，就试着教给别人。'],
  ['Clear thinking starts with clear words.', '清晰思考始于清晰表达。'],
  ['Small lessons create great wisdom.', '小小课程积成大智慧。'],
  ['Curiosity is the beginning of discovery.', '好奇心是发现的起点。'],
  ['An open mind learns twice.', '开放的心能学到双倍知识。'],

  ['Practice makes progress.', '练习带来进步。'],
  ['Effort is the bridge between goals and results.', '努力是目标与成果之间的桥梁。'],
  ['Little strokes fell great oaks.', '水滴石穿，积小成大。'],
  ['Where there is a will, there is a way.', '有志者事竟成。'],
  ['Nothing worth having comes easily.', '值得拥有的东西都来之不易。'],
  ['Hard work beats idle talent.', '勤奋胜过闲置的天赋。'],
  ['One step at a time reaches the summit.', '一步一个脚印，终能登顶。'],
  ['Repetition builds confidence.', '反复练习建立信心。'],
  ['Steady effort wins the long race.', '持续努力赢得长跑。'],
  ['Do the work, then trust the work.', '认真付出，然后相信成果。'],
  ['Strong habits carry weak motivation.', '好习惯能托住低落的动力。'],
  ['Begin before you feel ready.', '不必等准备完美再开始。'],
  ['Action is the best teacher.', '行动是最好的老师。'],
  ['Diligence turns dreams into plans.', '勤奋让梦想变成计划。'],
  ['Keep going when progress feels slow.', '进步缓慢时也要继续。'],
  ['The first try is only the beginning.', '第一次尝试只是开始。'],
  ['Daily practice makes difficult things familiar.', '每日练习让难事变熟悉。'],
  ['Consistency is quiet strength.', '坚持是一种安静的力量。'],
  ['Finish the small task in front of you.', '先完成眼前的小任务。'],
  ['A patient hand makes careful work.', '耐心的手能做出细致的成果。'],
  ['Great results grow from ordinary days.', '伟大成果生长于平凡日子。'],

  ['Time and tide wait for no one.', '岁月不等人。'],
  ['A stitch in time saves nine.', '及时处理，事半功倍。'],
  ['Early to bed and early to rise makes one healthy, wealthy, and wise.', '早睡早起使人健康、富足又明智。'],
  ['Make hay while the sun shines.', '把握时机，及时行动。'],
  ['Never put off until tomorrow what you can do today.', '今日事，今日毕。'],
  ['Well begun is half done.', '良好的开端是成功的一半。'],
  ['Lost time is never found again.', '失去的时间不会重来。'],
  ['Today is the best day to begin.', '今天就是开始的最好日子。'],
  ['Use each minute with purpose.', '让每一分钟都有意义。'],
  ['Good habits make hard days easier.', '好习惯让困难的日子更轻松。'],
  ['The morning hour has gold in its mouth.', '一日之计在于晨。'],
  ['Plan your work and work your plan.', '制定计划，并按计划行动。'],
  ['A calm routine creates steady progress.', '稳定的日常带来持续进步。'],
  ['One focused hour beats a distracted day.', '专注一小时胜过分心一整天。'],
  ['Start small, but start now.', '从小处开始，但现在就开始。'],
  ['The right time is the time you use.', '真正合适的时间，是你付诸行动的时间。'],
  ['Make room for what matters.', '为重要的事情留出时间。'],
  ['A daily plan protects your dreams.', '每日计划守护你的梦想。'],
  ['Rest well so you can learn well.', '好好休息，才能好好学习。'],
  ['Time rewards the prepared mind.', '时间会奖励有准备的人。'],
  ['Tomorrow improves when today is used well.', '用好今天，明天才会更好。'],

  ['Fall seven times, stand up eight.', '跌倒七次，也要第八次站起来。'],
  ['Smooth seas do not make skillful sailors.', '平静的海面练不出优秀的水手。'],
  ['After rain comes fair weather.', '雨过终会天晴。'],
  ['Every cloud has a silver lining.', '困境中总有希望。'],
  ['The darkest hour is just before dawn.', '黎明之前最黑暗。'],
  ['Difficult roads often lead to beautiful places.', '艰难的道路常通向美丽的地方。'],
  ['Courage grows each time you try again.', '每次重新尝试，勇气都会增长。'],
  ['A setback is not the end of the road.', '挫折不是道路的终点。'],
  ['Bend with the wind, but keep your roots.', '随风而弯，但守住根基。'],
  ['Patience can carry a heavy load.', '耐心能承载重担。'],
  ['Problems are invitations to grow.', '问题是成长的邀请。'],
  ['Strong minds recover and continue.', '强大的内心会恢复并继续前行。'],
  ['Begin again with what you know now.', '带着现在的经验重新开始。'],
  ['Hard days teach lasting lessons.', '艰难的日子带来长久的教训。'],
  ['Progress can be slow and still be real.', '进步可以缓慢，但依然真实。'],
  ['Keep your eyes on the next step.', '把目光放在下一步。'],
  ['Storms pass, but strength remains.', '风暴会过去，力量会留下。'],
  ['Failure is feedback for the next attempt.', '失败是下一次尝试的反馈。'],
  ['Hope is a light you can carry.', '希望是一束可以随身携带的光。'],
  ['A brave heart tries one more time.', '勇敢的心愿意再试一次。'],
  ['Every challenge hides a new skill.', '每个挑战都藏着一项新技能。'],

  ['Fortune favors the bold.', '幸运眷顾勇敢的人。'],
  ['Believe you can learn it.', '相信自己能够学会。'],
  ['Confidence grows from preparation.', '信心来自充分准备。'],
  ['Speak clearly and stand kindly.', '清晰表达，友善坚定。'],
  ['Courage begins with one honest step.', '勇气始于诚实的一步。'],
  ['Try the thing that teaches you most.', '尝试最能让你成长的事情。'],
  ['Your voice grows stronger when you use it.', '越勇于表达，声音越有力量。'],
  ['Do not fear a slow beginning.', '不要害怕缓慢的开始。'],
  ['Be willing to be a beginner.', '愿意做一个初学者。'],
  ['Preparation turns fear into focus.', '准备把恐惧变成专注。'],
  ['A calm mind makes brave choices.', '平静的心能做出勇敢的选择。'],
  ['Trust the progress you have earned.', '相信自己努力得来的进步。'],
  ['The answer may be one question away.', '答案也许只差一个问题。'],
  ['Face the task, not the worry.', '面对任务，而不是担忧。'],
  ['Confidence follows repeated effort.', '持续努力之后，信心自然到来。'],
  ['Dare to learn something difficult.', '敢于学习困难的事物。'],
  ['Be proud of progress, not perfection.', '为进步自豪，不必追求完美。'],
  ['Courage and kindness can share a voice.', '勇气与善意可以同时表达。'],
  ['Take the chance to improve.', '抓住让自己进步的机会。'],
  ['Your next attempt can be better.', '下一次尝试可以更好。'],
  ['Speak up when your idea can help.', '当你的想法有帮助时，勇敢说出来。'],

  ['Look before you leap.', '三思而后行。'],
  ['Measure twice, cut once.', '多检查一次，少返工一次。'],
  ['Two heads are better than one.', '三个臭皮匠，胜过一个诸葛亮。'],
  ['Better late than never.', '迟做总比不做好。'],
  ['Honesty is the best policy.', '诚实是最好的原则。'],
  ['Actions speak louder than words.', '行动胜于言语。'],
  ['Think twice and choose once.', '认真思考，再做选择。'],
  ['A clear goal makes choices easier.', '目标清晰，选择更容易。'],
  ['Listen to advice, then use your judgment.', '听取建议，也要独立判断。'],
  ['Wisdom begins by knowing what you do not know.', '智慧始于知道自己的未知。'],
  ['Simple answers often start with careful questions.', '简单的答案常始于认真的问题。'],
  ['Choose what helps you grow.', '选择能帮助你成长的事。'],
  ['Notice the pattern before making the rule.', '先观察规律，再总结规则。'],
  ['Good decisions need both facts and patience.', '好决定既需要事实，也需要耐心。'],
  ['A quiet mind can hear the truth.', '安静的心更容易听见真相。'],
  ['Learn from the past, but live in the present.', '向过去学习，活在当下。'],
  ['Think about the result before the action.', '行动之前先想结果。'],
  ['A wise person changes course when needed.', '明智的人会在必要时调整方向。'],
  ['Facts are friends of clear thinking.', '事实是清晰思考的朋友。'],
  ['Good judgment grows through reflection.', '良好判断力来自反思。'],
  ['The best answer may begin with "why."', '最好的答案也许始于为什么。'],

  ['Kind words cost nothing.', '好话不花钱。'],
  ['Treat others as you wish to be treated.', '己所欲，亦施于人。'],
  ['A good name is better than riches.', '好名声胜过财富。'],
  ['Kindness is never wasted.', '善意永远不会被浪费。'],
  ['Respect opens doors that force cannot.', '尊重能打开强力打不开的门。'],
  ['Be honest, even when no one is watching.', '即使无人看见，也要诚实。'],
  ['A gentle answer can calm a storm.', '温和的回答能平息风暴。'],
  ['Good manners make learning easier.', '良好的礼貌让学习更顺利。'],
  ['Help others rise as you rise.', '自己进步时，也帮助他人进步。'],
  ['Gratitude makes enough feel abundant.', '感恩让已有的一切显得丰盛。'],
  ['Keep your promise and earn trust.', '信守承诺，赢得信任。'],
  ['Patience is kindness with time.', '耐心是带着时间的善意。'],
  ['Share credit and accept responsibility.', '分享功劳，承担责任。'],
  ['Character is built by daily choices.', '品格由每日选择塑造。'],
  ['Speak the truth with care.', '用体贴的方式说真话。'],
  ['Be firm in purpose and gentle with people.', '目标坚定，待人温和。'],
  ['A helpful hand teaches twice.', '帮助别人，也会让自己再学一次。'],
  ['Respect differences and seek understanding.', '尊重差异，寻求理解。'],
  ['The best strength protects others.', '最好的力量会保护他人。'],
  ['Kindness makes teamwork stronger.', '善意让团队合作更有力量。'],
  ['Do good quietly and consistently.', '安静而持续地做好事。'],

  ['Many hands make light work.', '人多力量大。'],
  ['United we stand, divided we fall.', '团结则立，分裂则败。'],
  ['A chain is only as strong as its weakest link.', '团队的力量取决于最薄弱的一环。'],
  ['Listen first and answer better.', '先倾听，才能更好地回答。'],
  ['Clear words prevent needless confusion.', '清晰表达能避免不必要的误解。'],
  ['Share ideas, not just answers.', '分享想法，不只分享答案。'],
  ['Teamwork turns effort into momentum.', '团队合作让努力形成动力。'],
  ['Ask for help before a problem grows.', '在问题扩大之前寻求帮助。'],
  ['Good listeners learn from every voice.', '善于倾听的人能从每个声音中学习。'],
  ['Explain simply to understand deeply.', '能简单讲清，才算真正理解。'],
  ['Cooperation makes difficult work lighter.', '合作让困难的工作变轻松。'],
  ['Different ideas can build one strong plan.', '不同想法可以共同构成好计划。'],
  ['Give feedback that helps the next attempt.', '给出能帮助下一次尝试的反馈。'],
  ['A shared goal gives a team direction.', '共同目标为团队指明方向。'],
  ['Speak to be understood, and listen to understand.', '表达是为了被理解，倾听是为了理解。'],
  ['The best teams make room for questions.', '优秀团队会为问题留出空间。'],
  ['Solve the problem, not the person.', '解决问题，不针对个人。'],
  ['Trust grows through reliable actions.', '信任在可靠行动中增长。'],
  ['Learn together and improve together.', '一起学习，一起进步。'],
  ['Good communication begins with attention.', '良好沟通始于专注。'],
  ['One thoughtful voice can improve the whole team.', '一个深思熟虑的声音能改善整个团队。'],

  ['Necessity is the mother of invention.', '需要是发明之母。'],
  ['Think outside the box, then test the idea.', '跳出框架思考，再检验想法。'],
  ['Focus turns effort into progress.', '专注让努力变成进步。'],
  ['Creativity begins with curiosity.', '创造力始于好奇心。'],
  ['A clear desk can support a clear mind.', '整洁的桌面有助于清晰思考。'],
  ['Give one task your full attention.', '把全部注意力交给一项任务。'],
  ['New ideas need room to grow.', '新想法需要成长空间。'],
  ['Observe closely and imagine freely.', '细致观察，自由想象。'],
  ['Create first, improve second.', '先创造，再改进。'],
  ['A fresh question can reveal a fresh path.', '新问题能揭示新路径。'],
  ['Simplicity is the result of careful thinking.', '简洁是认真思考的结果。'],
  ['Connect old ideas in new ways.', '用新方式连接旧想法。'],
  ['Let your mind explore, then let evidence guide.', '让思维探索，让证据引路。'],
  ['Focus on what you can change.', '专注于你能改变的事情。'],
  ['Good ideas become useful through testing.', '好想法经过检验才会变得有用。'],
  ['Imagination gives knowledge new directions.', '想象力为知识带来新方向。'],
  ['Quiet attention notices hidden details.', '安静的专注能发现隐藏的细节。'],
  ['Make space for deep work.', '为深度工作留出空间。'],
  ['A creative mind welcomes unusual connections.', '创造性的头脑欢迎不同寻常的联系。'],
  ['The simplest useful idea often wins.', '最简单且有用的想法常常胜出。'],
  ['Wonder is fuel for discovery.', '惊奇是发现的燃料。'],

  ['Reading is to the mind what exercise is to the body.', '阅读之于心灵，犹如运动之于身体。'],
  ['The pen is mightier than the sword.', '笔锋胜于剑锋。'],
  ['Words have power, so choose them well.', '语言有力量，所以要谨慎选择。'],
  ['A book is a garden carried in the pocket.', '书是装在口袋里的花园。'],
  ['Reading opens windows to other lives.', '阅读打开通往他人生活的窗。'],
  ['Every new word is a new tool.', '每个新词都是一件新工具。'],
  ['Write clearly to think clearly.', '清晰写作帮助清晰思考。'],
  ['Stories make distant ideas feel close.', '故事让遥远的想法变得亲近。'],
  ['Language connects minds and cultures.', '语言连接心灵与文化。'],
  ['Read with questions, not just with eyes.', '带着问题阅读，而不只是用眼睛阅读。'],
  ['A rich vocabulary gives ideas more room.', '丰富的词汇给思想更多空间。'],
  ['Good writing begins with careful reading.', '好写作始于认真阅读。'],
  ['Say less, but mean it well.', '话不必多，意思要清楚。'],
  ['The right word can light a dark thought.', '恰当的词能照亮模糊的思想。'],
  ['Reading slowly can reveal more.', '慢慢阅读能发现更多。'],
  ['Write often, revise kindly.', '常写作，耐心修改。'],
  ['A sentence improves when every word has a job.', '当每个词都有作用时，句子就会更好。'],
  ['Listen for meaning, not only sound.', '倾听意义，而不只是声音。'],
  ['Speak often to make a new language familiar.', '经常开口，让新语言变得熟悉。'],
  ['Translation builds bridges between worlds.', '翻译在不同世界之间搭建桥梁。'],
  ['Words remembered today become confidence tomorrow.', '今天记住的词汇，会成为明天的信心。']
].map(([english, chinese]) => ({ english, chinese }))
