#!/usr/bin/env python3
"""Build Yilin 4A (2024) word + sentence data from textbook Word lists (PDF p78-82)."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'data' / 'textbooks' / 'yilin-primary-4a-2024.json'

# Words grouped by unit per textbook Word list (by unit), p78-80.
# Each entry: word, translation, core (no *), sentence, sentenceCn
UNITS = [
  {
    'unit': 1,
    'title': 'Our school subjects',
    'words': [
      ('subject', '学科，科目', True, 'What subject do you like best?', '你最喜欢什么学科？'),
      ('Chinese', '语文（课）；中国的', True, 'I like Chinese best.', '我最喜欢语文。'),
      ('English', '英语（课）；英语的', True, 'I like reading English stories.', '我喜欢读英语故事。'),
      ('Maths', '数学（课）', True, 'I like Maths. I\'m good at it.', '我喜欢数学，我很擅长。'),
      ('PE', '体育（课）', True, 'It\'s time for PE.', '该上体育课了。'),
      ('Art', '美术（课）', True, 'We also have Art, PE and Music.', '我们还有美术、体育和音乐课。'),
      ('Science', '科学（课）', True, 'Science is interesting.', '科学课很有趣。'),
      ('IT', '信息科技（课）', False, 'I also like IT.', '我也喜欢信息科技课。'),
      ('Music', '音乐（课）', True, 'I like Music best.', '我最喜欢音乐课。'),
      ('Labour', '劳动（课）', False, 'We have Chinese, Maths, English and Science.', '我们有语文、数学、英语和科学课。'),
      ('best', '最，最高程度地', True, 'What subject do you like best?', '你最喜欢什么学科？'),
      ('also', '也', True, 'We also have Art, PE and Music.', '我们还有美术、体育和音乐课。'),
      ('It\'s time for ...', '是……的时候了。', True, 'It\'s time for PE.', '该上体育课了。'),
      ('mouse', '鼠标；老鼠', True, 'Mouse? I\'m here!', '老鼠？我在这儿！'),
      ('Welcome back to ...', '欢迎回到……', True, 'Welcome back to school, class.', '欢迎回到学校，同学们。'),
      ('be good at', '擅长', True, 'I\'m good at Maths.', '我擅长数学。'),
      ('interesting', '有趣的，有吸引力的', True, 'Science is interesting.', '科学课很有趣。'),
      ('learn about', '学习', True, 'I want to learn about Chinese culture.', '我想了解中国文化。'),
      ('culture', '文化，文明', False, 'I want to learn about Chinese culture.', '我想了解中国文化。'),
      ('read', '阅读', True, 'I like reading English stories.', '我喜欢读英语故事。'),
      ('story', '故事', True, 'I like reading English stories.', '我喜欢读英语故事。'),
      ('all', '全部，都', True, 'We all like PE!', '我们都喜欢体育课！'),
      ('sports ground', '操场，运动场', False, 'Let\'s go to the sports ground!', '我们去操场吧！'),
    ],
  },
  {
    'unit': 2,
    'title': 'My day',
    'words': [
      ('day', '一天，一日', True, 'What do you do every day?', '你每天做什么？'),
      ('get up', '起床', True, 'Bobby, get up! It\'s seven o\'clock.', '博比，起床！七点了。'),
      ('wash', '洗', True, 'Wash your face first, Bobby.', '博比，先洗脸。'),
      ('face', '脸，面孔', True, 'Wash your face first, Bobby.', '博比，先洗脸。'),
      ('have lessons', '上课', True, 'We have lessons at school.', '我们在学校上课。'),
      ('have', '吃，喝', True, 'It\'s time for breakfast.', '该吃早餐了。'),
      ('dinner', '正餐（常指晚餐）', True, 'We have dinner in the evening.', '我们晚上吃正餐。'),
      ('breakfast', '早餐，早饭', True, 'It\'s time for breakfast.', '该吃早餐了。'),
      ('lunch', '午餐，午饭', True, 'We have lunch at twelve o\'clock.', '我们十二点吃午餐。'),
      ('go to bed', '上床睡觉', True, 'I go to bed at nine o\'clock.', '我九点上床睡觉。'),
      ('o\'clock', '（表示整点）……点钟', True, 'It\'s seven o\'clock.', '七点了。'),
      ('early', '早的，早', True, 'It\'s early.', '还早呢。'),
      ('thirty', '三十', True, 'It\'s seven thirty!', '七点半了！'),
      ('first', '首先，第一', True, 'Wash your face first, Bobby.', '博比，先洗脸。'),
      ('hurry up', '快点', True, 'Bobby, hurry up!', '博比，快点！'),
      ('What time is it?', '几点了？', True, 'What time is it now?', '现在几点了？'),
      ('I\'m coming!', '我来了！', True, 'I\'m coming!', '我来了！'),
      ('twenty', '二十', True, 'It\'s twenty past seven.', '七点二十分。'),
      ('Come on!', '赶快！加把劲！', True, 'Come on! Let\'s go!', '快点！我们走吧！'),
      ('class', '课，上课', True, 'Welcome back to school, class.', '欢迎回到学校，同学们。'),
      ('eleven', '十一', True, 'It\'s eleven o\'clock.', '十一点了。'),
      ('sport', '体育运动', True, 'Sport is good for us.', '体育运动对我们有好处。'),
      ('fifteen', '十五', True, 'It\'s fifteen past eight.', '八点十五分。'),
      ('It\'s time to ...', '到了……的时间了。', True, 'Get up now—it\'s time to go.', '现在起床——该走了。'),
      ('bed', '床', True, 'Bobby is still in bed.', '博比还在床上。'),
      ('Good night!', '晚安！', True, 'Good night, Mum!', '晚安，妈妈！'),
    ],
  },
  {
    'unit': 3,
    'title': 'My week',
    'words': [
      ('week', '周，星期', True, 'How do you plan your week?', '你怎么制订一周计划？'),
      ('Monday', '星期一', True, 'I have a dancing lesson on Monday.', '我星期一有舞蹈课。'),
      ('Tuesday', '星期二', True, 'We go to the cinema on Tuesday.', '我们星期二去电影院。'),
      ('Wednesday', '星期三', True, 'What do you want to do on Wednesday?', '你星期三想做什么？'),
      ('Thursday', '星期四', True, 'I walk my dog on Thursday.', '我星期四遛狗。'),
      ('Friday', '星期五', True, 'It\'s Friday today.', '今天是星期五。'),
      ('Saturday', '星期六', True, 'I am free on Saturday.', '我星期六有空。'),
      ('Sunday', '星期天', True, 'We fly a kite on Sunday.', '我们星期天放风筝。'),
      ('when', '什么时候', True, 'When do you go to the cinema?', '你什么时候去电影院？'),
      ('every', '每一个，每个', True, 'What do you do every day?', '你每天做什么？'),
      ('at', '在（某时间）', True, 'I go to bed at nine o\'clock.', '我九点上床睡觉。'),
      ('up', '起床', True, 'Get up now—it\'s time to go.', '现在起床——该走了。'),
      ('early', '提早，提前', True, 'I want to go to school early.', '我想早点去学校。'),
      ('today', '在今天', True, 'What day is it today?', '今天星期几？'),
      ('What day is it today?', '今天星期几？', True, 'What day is it today?', '今天星期几？'),
      ('cinema', '电影院', True, 'Let\'s go to the cinema after school.', '放学后我们去看电影吧。'),
      ('after school', '放学后', True, 'I walk my dog after school.', '我放学后遛狗。'),
      ('dancing', '跳舞，舞蹈', True, 'I have a dancing lesson on Monday.', '我星期一有舞蹈课。'),
      ('lesson', '一节课，一课时', True, 'I have a dancing lesson on Monday.', '我星期一有舞蹈课。'),
      ('walk', '牵着（动物）走，遛', True, 'I walk my dog after school.', '我放学后遛狗。'),
      ('dog', '狗', True, 'I walk my dog after school.', '我放学后遛狗。'),
      ('tomorrow', '明天；在明天', True, 'See you tomorrow!', '明天见！'),
      ('free', '空闲的', True, 'I am free tomorrow.', '我明天有空。'),
      ('See you tomorrow!', '明天见！', True, 'See you tomorrow!', '明天见！'),
    ],
  },
  {
    'unit': 4,
    'title': 'I like sport',
    'words': [
      ('play', '打（球），踢（球）', True, 'Let\'s go and play.', '我们去玩吧。'),
      ('football', '足球运动；足球', True, 'Do you like playing football?', '你喜欢踢足球吗？'),
      ('ping-pong', '乒乓球运动', True, 'Ping-pong is fun.', '乒乓球很有趣。'),
      ('basketball', '篮球运动；篮球', True, 'I like playing basketball.', '我喜欢打篮球。'),
      ('great', '非常的', True, 'You play so well!', '你打得真好！'),
      ('swimming', '游泳；游泳运动', True, 'I like swimming and playing ping-pong.', '我喜欢游泳和打乒乓球。'),
      ('so', '（表示程度）这么，那么', True, 'You play so well!', '你打得真好！'),
      ('well', '好', True, 'You play so well!', '你打得真好！'),
      ('Have a go!', '试一试！', True, 'Have a go!', '试一试！'),
      ('hard', '难做的，不易的', True, 'Ping-pong is fun, but I can\'t play well.', '乒乓球很有趣，但我打得不好。'),
      ('It\'s OK.', '没关系。', True, 'It\'s OK. Try again.', '没关系，再试一次。'),
      ('try', '试', True, 'It\'s OK. Try again.', '没关系，再试一次。'),
      ('Well played!', '好球！', True, 'Well played!', '好球！'),
    ],
  },
  {
    'unit': 5,
    'title': 'Different toys, same fun',
    'words': [
      ('different', '不同的，有区别的', False, 'Our toys are different.', '我们的玩具各不相同。'),
      ('same', '相同的，同一的', False, 'Different toys, same fun.', '玩具不同，乐趣相同。'),
      ('hair', '头发', True, 'Her hair is long.', '她的头发很长。'),
      ('eye', '眼睛', True, 'Her eyes are big.', '她的眼睛很大。'),
      ('ear', '耳朵', True, 'The robot has small ears.', '这个机器人耳朵很小。'),
      ('nose', '鼻子', True, 'Her nose is small.', '她的鼻子很小。'),
      ('mouth', '嘴，口', True, 'Her nose and mouth are small.', '她的鼻子和嘴巴都很小。'),
      ('arm', '手臂', True, 'His arms are long.', '他的手臂很长。'),
      ('leg', '腿', True, 'You\'re so tall! Your legs are long.', '你真高！你的腿很长。'),
      ('robot', '机器人', True, 'These robots are cool!', '这些机器人很酷！'),
      ('his', '他的', True, 'His face is lovely.', '他的脸很可爱。'),
      ('tall', '高的', True, 'You\'re so tall!', '你真高！'),
      ('short', '短的', True, 'His legs are long, not short.', '他的腿很长，不短。'),
      ('doll', '玩具娃娃', True, 'Mum, do you like our dolls?', '妈妈，你喜欢我们的娃娃吗？'),
      ('her', '她的', True, 'Look at her lovely face.', '看她可爱的脸。'),
      ('small', '小的', True, 'Her nose and mouth are small.', '她的鼻子和嘴巴都很小。'),
      ('bring', '带来', True, 'The toys bring you lots of fun.', '这些玩具给你带来很多乐趣。'),
      ('lots of', '大量，许多', True, 'The toys bring you lots of fun.', '这些玩具给你带来很多乐趣。'),
      ('have', '组织，举办', True, 'Let\'s have a puppet show.', '我们来办一场木偶表演吧。'),
      ('show', '表演，演出', True, 'Let\'s have a puppet show.', '我们来办一场木偶表演吧。'),
    ],
  },
  {
    'unit': 6,
    'title': 'Weather',
    'words': [
      ('weather', '天气，气象', True, 'What\'s the weather like today?', '今天天气怎么样？'),
      ('cloudy', '多云的，阴天的', True, 'On Friday, it is cloudy.', '星期五多云。'),
      ('sunny', '晴朗的', True, 'On Sunday, it is sunny.', '星期天晴朗。'),
      ('cool', '凉的，凉爽的', True, 'It is cool today.', '今天很凉爽。'),
      ('rainy', '阴雨的，多雨的', True, 'On Saturday, it is rainy.', '星期六下雨。'),
      ('hot', '温度高的，热的', True, 'It is hot in summer.', '夏天很热。'),
      ('windy', '多风的，风大的', True, 'It is windy today.', '今天风很大。'),
      ('warm', '温暖的，暖和的', True, 'It is warm in spring.', '春天很温暖。'),
      ('save ... for a rainy day', '未雨绸缪', False, 'Save your money for a rainy day.', '把钱存起来以备不时之需。'),
      ('money', '钱', True, 'Save your money for a rainy day.', '把钱存起来以备不时之需。'),
      ('What\'s the weather like today?', '今天天气怎么样？', True, 'What\'s the weather like today?', '今天天气怎么样？'),
      ('park', '公园', True, 'Let\'s go to the park.', '我们去公园吧。'),
      ('meet', '（与……）会面，集合', True, 'Let\'s meet at the park.', '我们在公园见面吧。'),
      ('fly a kite', '放风筝', True, 'We can fly a kite on a windy day.', '刮风天我们可以放风筝。'),
      ('It\'s raining.', '下雨了。', True, 'It\'s raining. Take an umbrella.', '下雨了，带把伞。'),
      ('worry', '担心，担忧', True, 'Don\'t worry.', '别担心。'),
      ('umbrella', '伞，雨伞', True, 'Take an umbrella with you.', '你带把伞吧。'),
      ('there', '到那里，在那里', True, 'Let\'s meet there.', '我们在那里见面吧。'),
    ],
  },
  {
    'unit': 7,
    'title': 'Seasons',
    'words': [
      ('season', '季节', True, 'What do you do in different seasons?', '你在不同季节做什么？'),
      ('spring', '春天，春季', True, 'In spring, it is warm.', '春天很温暖。'),
      ('go boating', '去划船', True, 'We go boating in spring.', '春天我们去划船。'),
      ('winter', '冬天，冬季', True, 'It is cold in winter.', '冬天很冷。'),
      ('go skating', '去溜冰，去滑冰', False, 'We go skating in winter.', '冬天我们去滑冰。'),
      ('summer', '夏天，夏季', True, 'In summer, we eat ice cream.', '夏天我们吃冰激凌。'),
      ('ice cream', '冰激凌', True, 'In summer, we eat ice cream.', '夏天我们吃冰激凌。'),
      ('go swimming', '去游泳', True, 'We go swimming in summer.', '夏天我们去游泳。'),
      ('autumn', '秋天，秋季', True, 'In autumn, it is cool.', '秋天很凉爽。'),
      ('go climbing', '去爬山', False, 'We go climbing in autumn.', '秋天我们去爬山。'),
      ('new', '新的', True, 'Spring is a new season.', '春天是一个新的季节。'),
      ('cold', '寒冷的，冷的', True, 'It is cold in winter.', '冬天很冷。'),
      ('bird', '鸟', True, 'The birds come back in spring.', '鸟儿在春天回来。'),
      ('back', '回原处', True, 'The birds come back in spring.', '鸟儿在春天回来。'),
      ('in', '在（某段时间）内', True, 'In spring, we plant trees.', '春天我们种树。'),
      ('year', '年', True, 'There are four seasons in a year.', '一年有四个季节。'),
      ('plant', '栽种，种植', True, 'In spring, we plant trees.', '春天我们种树。'),
      ('pick', '采，摘', False, 'In autumn, we pick fruit.', '秋天我们摘果子。'),
      ('snow', '雪，积雪', True, 'It snows in winter.', '冬天下雪。'),
    ],
  },
  {
    'unit': 8,
    'title': 'What we wear',
    'words': [
      ('wear', '穿，戴', True, 'What do you wear for special days?', '特殊日子里你穿什么？'),
      ('cap', '（尤指有帽舌的）便帽', True, 'You look cool in the cap.', '你戴这顶帽子看起来很酷。'),
      ('coat', '外套，外衣', True, 'This is my mother\'s coat.', '这是我妈妈的外套。'),
      ('skirt', '半身裙', True, 'She wears a new skirt.', '她穿了一条新半身裙。'),
      ('trousers', '裤子', True, 'Whose trousers are these?', '这是谁的裤子？'),
      ('dress', '连衣裙', True, 'She wears a red dress.', '她穿了一条红色连衣裙。'),
      ('shirt', '（男式）衬衫', True, 'This is my father\'s new shirt.', '这是我爸爸的新衬衫。'),
      ('whose', '谁的', True, 'Whose cap is it?', '它是谁的帽子？'),
      ('shorts', '短裤', True, 'Whose shorts are these?', '这是谁的短裤？'),
      ('look', '看来好像，显得', True, 'You look cool in the cap.', '你戴这顶帽子看起来很酷。'),
      ('in', '穿着，戴着', True, 'You look cool in the cap.', '你戴这顶帽子看起来很酷。'),
      ('sunglasses', '太阳镜，墨镜', False, 'I wear sunglasses because they\'re cool.', '我戴太阳镜因为它很酷。'),
      ('why', '为什么', True, 'Why do I wear sunglasses today?', '我今天为什么戴太阳镜？'),
      ('because', '因为', True, 'I wear sunglasses because they\'re cool.', '我戴太阳镜因为它很酷。'),
      ('bright', '聪明的；明亮的', False, 'My students are very bright!', '我的学生们非常聪明！'),
      ('clothes', '衣服', True, 'What clothes do you wear?', '你穿什么衣服？'),
    ],
  },
]

payload = {
  'meta': {
    'press': '牛津译林版',
    'edition': '译林版（三起）（2024）',
    'grade': '四年级',
    'semester': '上册',
    'sourcePdf': '18365106.pdf',
    'sourcePages': 'Word lists p78-82; sentences from Story time / Cartoon time',
    'unitCount': len(UNITS),
    'wordCount': sum(len(u['words']) for u in UNITS),
  },
  'units': [
    {
      'unit': u['unit'],
      'title': u['title'],
      'words': [
        {
          'content': w[0],
          'translation': w[1],
          'core': w[2],
          'sentence': w[3],
          'sentenceCn': w[4],
        }
        for w in u['words']
      ],
    }
    for u in UNITS
  ],
}

OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(f'Wrote {OUT} ({payload["meta"]["wordCount"]} words, {payload["meta"]["unitCount"]} units)')
